feat: Safe creation AB test
safe-global/web-core pull request #1001
Opened 2022-10-28 12:05 UTC by iamacook

## What it solves

Resolves #968

## How this PR fixes it

An "coin toss" decides which Safe creation flow to use (new or old) and stores this flag locally. The chosen flow is also sent with every analytics event.

## How to test it

Open Safe creation (from `/welcome`) and note which flow is chosen. Return to `/welcome`, delete the `SAFE_v2__AB__newSafe` `localStorage` entry and refresh the page. Creating a Safe again may choose a different flow. Repeat until the other is taken.

## Analytics changes

`{ abTest?: string }` is sent with events in Safe load/creation, labelled "New" or "Old" accordingly.

2022-10-28 12:06 UTC, iamacook commented on src/config/routes.ts
> +    add: '/new-safe/add',
This was added in anticipation of the add Safe revamp.

2022-10-28 12:06 UTC, iamacook commented on src/hooks/useNewSafeRoutes.ts
> +    addSafe: shouldUseNewRoute ? AppRoutes.newSafe.add : AppRoutes.load,
`AppRoutes.newSafe.add` uses the `AppRoutes.load` component for now.

2022-10-28 18:40 UTC, katspaugh commented
It would be much simpler to just add a conditional redirect on the old URL.

2022-10-31 09:53 UTC, katspaugh requested changes
To make my point about the redirect clear, instead of the `useNewSafeRoutes` spread across many components, the A/B test should have just one entry point: the old Safe creation route.
On that page, do a simple URL redirect to the alternative URL if the user is in B.

As a side note, I would split this PR into two:
* A/B test system implementation
* The Safe creation test

2022-10-31 10:05 UTC, iamacook commented
> As a side note, I would split this PR into two:
> 
>     * A/B test system implementation
> 
>     * The Safe creation test

I'll work on this now.

2022-10-31 10:05 UTC, closed without merging