refactor: instantiate contracts via Core SDK
safe-global/web-core pull request #497
Opened 2022-09-01 15:54 UTC by iamacook

## What it solves

Using the Core SDK to get contract instances.

## How this PR fixes it

All (possible) contract instance retrievals are now done via the Core SDK so that we rely less on TypeChain.

## How to test it

- Safe creation and associated gas estimation works as expected.
- Interrupted Safe creation transactions succeed.
- Batch execution works as expected.
- Safe updating works as expected.

2022-09-02 07:44 UTC, usame-algan requested changes
There is a missing dependency. Should we also remove the typechain files and configs now that the contracts are not used anymore?

2022-09-02 07:44 UTC, usame-algan commented on src/components/tx/modals/BatchExecuteModal/ReviewBatchExecute.tsx
> -    <div>
This wrapper is needed with TxModal for the spacing. We could refactor this separately though.
<img width="632" alt="Screenshot 2022-09-02 at 09 43 15" src="https://user-images.githubusercontent.com/5880855/188085167-0f765581-a5ba-4045-b5e7-eacb72bdc5cc.png">

2022-09-02 08:15 UTC, iamacook commented
@usame-algan, I've restored the wrapper, as well as added the missing dependency.

Not all contract instances are retrieved from the SDK yet. I think we should leave it as is for now.

2022-09-02 09:25 UTC, usame-algan approved these changes

2022-09-02 09:27 UTC, merged

2022-09-09 06:02 UTC, francovenica commented
I've tried several tx in different situations like the ones mentioned in the description and they worked fine. 
I'll keep checking tx during the next week, if any issue is found it will be reported in a separed ticket