feat: error boundary
safe-global/web-core pull request #509
Opened 2022-09-05 08:32 UTC by iamacook

## What it solves

Inclusion of an Error Boundary `fallback`.

## How this PR fixes it

A `fallback` component has been created to match that of `safe-react` and is passed to `Sentry.ErrorBoundary`.

## How to test it

Locally edit the `AppProviders` to the following and observe the new component in the browser.

```ts
export const AppProviders = ({ children }: { children: ReactNode | ReactNode[] }) => {
  const theme = useLightDarkTheme()

  return (
    <ThemeProvider theme={theme}>
      <ErrorBoundary error={new Error('Test')} />
    </ThemeProvider>
  )
}
```

## Screenshots

![image](https://user-images.githubusercontent.com/20442784/188405108-5a45c8f0-9391-4868-bf1d-d211b54b51e3.png)

2022-09-05 08:33 UTC, iamacook commented on src/pages/_app.tsx
> +    </CacheProvider>
We require the theme inside `ErrorBoundary`.

2022-09-05 10:15 UTC, usame-algan requested changes

2022-09-05 10:15 UTC, usame-algan commented on src/components/common/icons/KeyholeIcon/index.tsx
> +}
This seems a bit much for something we could have 2 svgs for:

Keyhole:
```
<svg width="60" height="60" viewBox="0 0 60 60" fill="none" xmlns="http://www.w3.org/2000/svg">
<circle cx="30" cy="30" r="30" fill="#E8E7E6"/>
<path fill-rule="evenodd" clip-rule="evenodd" d="M27.031 43.575H34.3407C35.0771 43.575 35.6741 42.9781 35.6741 42.2417C35.6741 42.17 35.6683 42.0985 35.6568 42.0278L33.7781 30.4703C36.1541 29.3307 37.8041 26.9374 37.8041 24.1567C37.8041 20.2858 34.619 17.1431 30.6878 17.1431C26.7596 17.1431 23.5715 20.2858 23.5715 24.1567C23.5672 26.9402 25.2144 29.3307 27.5961 30.4703L25.715 42.0275C25.5967 42.7543 26.09 43.4394 26.8168 43.5577C26.8876 43.5692 26.9593 43.575 27.031 43.575Z" fill="#B2B5B2"/>
<circle cx="52" cy="52" r="7" fill="#F02525" stroke="white" stroke-width="2"/>
</svg>
```

Warning:
```
<svg xmlns="http://www.w3.org/2000/svg" width="90" height="90" viewBox="0 0 90 90"><g fill="none" fill-rule="evenodd"><circle cx="45" cy="45" r="45" fill="#E8E7E6"></circle><path fill="#B2B5B2" fill-rule="nonzero" d="M26.24 62c-.57 0-1.13-.15-1.623-.437a3.254 3.254 0 0 1-1.18-4.44l18.76-32.501a3.234 3.234 0 0 1 5.606 0l18.761 32.501c.286.495.436 1.057.436 1.628A3.244 3.244 0 0 1 63.76 62H26.24z"></path><path fill="#E8E7E6" fill-rule="nonzero" d="M47 49h-4V36h4zM47 55h-4v-4h4z"></path><circle cx="78" cy="78" r="11" fill="#FFC05F" fill-rule="nonzero" stroke="#F6F7F8" stroke-width="4"></circle></g></svg>
```

2022-09-05 13:44 UTC, usame-algan approved these changes

2022-09-05 13:44 UTC, merged

2022-09-06 12:23 UTC, francovenica commented
LGTM
Changes the files in my local and the error page came out fine. 
I'll remember to check it again if the page crashes for some reason.