refactor: currency formatting
safe-global/web-core pull request #552
Opened 2022-09-16 09:34 UTC by iamacook

## What it solves

Resolves currency style

## How this PR fixes it

The `Intl.NumberFormat` logic for amounts been refactored so that currency/amounts adhere to the same style.

Currency formatting now displays the currency code at the end of the amount which matches our desired design.

## How to test it

Observe no differences in amounts across the Safe, apart from the sidebar header showing currencies appended with the relevant currency code.

The currencies should be rounded to the country-specific precision, e.g. JPY has no decimals, EUR has two, IQD has three.

## Screenshots

![image](https://user-images.githubusercontent.com/20442784/190606633-f8d6a394-0479-4a3a-a54a-199b2bcf6fec.png)
![image](https://user-images.githubusercontent.com/20442784/190606758-1c3a5241-437c-4616-b0c2-fbe45b1465de.png)
![image](https://user-images.githubusercontent.com/20442784/190606560-7738a9e4-adae-44ad-8dff-a595aa69517c.png)

2022-09-16 12:16 UTC, DiogoSoaress commented on src/utils/__tests__/formatNumber.test.ts
> +      expect(formatCurrency(amount2, 'BHD')).toBe('0.123 BHD')
why has this currency 3 decimals?

2022-09-16 12:27 UTC, iamacook commented on src/utils/__tests__/formatNumber.test.ts
> +      expect(formatCurrency(amount2, 'BHD')).toBe('0.123 BHD')
All Dinar have three decimal places.

2022-09-16 12:31 UTC, iamacook commented on src/utils/__tests__/formatNumber.test.ts
> +    it("doesn't use < -0.00001 or < +0.00001 when the Eucledian distance of the amount is smaller than 0.00001", () => {
Currencies are formatted to their native precision.

2022-09-16 12:31 UTC, iamacook commented on src/utils/__tests__/formatNumber.test.ts
> +    it('should use T notation for numbers between 999,999,500,000 and 999,000,000,000', () => {
Different currencies have varying decimal precision.

2022-09-16 12:31 UTC, iamacook commented on src/utils/__tests__/formatNumber.test.ts
> +    it('should use B symbol for numbers between 999,999,500 and 999,999,500,000', () => {
Different currencies have varying decimal precision.

2022-09-16 12:37 UTC, iamacook commented on src/utils/formatNumber.ts
> +    typeof number === 'string' ? number.includes('+') || number.includes('-') : Math.sign(float) === -1
> I think it's safer to trim the string and use `startsWith`

`includes` checks all indexes of a string.

>In general I feel it's cleaner to pass that check to outside the ternary. We should check for the - sign with something like

If we wanted to check against `float`, we would still need to use `Math.abs(float)`. I feel like using the native sign function is the most declarative.

2022-09-16 15:39 UTC, DiogoSoaress requested changes

2022-09-16 15:39 UTC, DiogoSoaress commented on src/utils/__tests__/formatNumber.test.ts
> +      const amount2 = '0.123456789'
The `amount2` rounds always down for the tested currencies. I would add a `amount3 = 1.7777` (per example) to test if the rounding up is working as expected as well.

2022-09-16 15:39 UTC, DiogoSoaress commented on src/utils/__tests__/formatNumber.test.ts
> +      expect(formatCurrency(amount2, 'JPY')).toBe('1.2B JPY')
shouldn't it display `1.235B JPY` ?

2022-09-16 15:39 UTC, DiogoSoaress commented on src/utils/__tests__/formatNumber.test.ts
> +      expect(formatCurrency(amount2, 'JPY')).toBe('1.2T JPY')
`1.234T JPY` ?

2022-09-16 15:57 UTC, DiogoSoaress commented on src/utils/__tests__/formatNumber.test.ts
> +      expect(formatCurrency(amount2, 'JPY')).toBe('1.2B JPY')
Resolving as the number of fraction digits comes from the currency formatter

2022-09-16 15:57 UTC, DiogoSoaress commented on src/utils/__tests__/formatNumber.test.ts
> +      expect(formatCurrency(amount2, 'JPY')).toBe('1.2T JPY')
Resolving as the number of fraction digits comes from the currency formatter

2022-09-16 15:58 UTC, DiogoSoaress approved these changes
👍

2022-09-16 16:39 UTC, merged

2022-09-19 04:21 UTC, francovenica commented
LGTM