fix: Display multisend actions when executing batch
safe-global/web-core pull request #714
Opened 2022-09-28 09:50 UTC by usame-algan

## What it solves

Resolves #662 

## How this PR fixes it

Reuses the `Multisend` component to display individual actions of a multisend tx when executing a batch.

Some actions are missing information in the decoded data response. These include On-chain rejections and Native token transfers. This is a general issue with the `Multisend` component and should be fixed separately.

## How to test it

1. Open the Safe
2. Queue up a couple transactions
3. Click the Batch Execute button
4. Observe loading skeletons
5. Observe actions being displayed the same way as they are in Safe Apps and Tx Details

## Screenshots
<img width="624" alt="Screenshot 2022-09-28 at 11 47 52" src="https://user-images.githubusercontent.com/5880855/192747838-e00a987f-3277-4774-84a4-41889e8d1bc9.png">

2022-09-28 12:24 UTC, DiogoSoaress commented
> Some actions are missing information in the decoded data response. These include On-chain rejections and Native token transfers. This is a general issue with the Multisend component and should be fixed separately.

Can you point or open an issue to keep track of this?

2022-09-28 12:30 UTC, DiogoSoaress requested changes
By using the `<Multisend />` we are changing the Accordion style we had previously.

2022-09-28 14:33 UTC, usame-algan commented
> By using the <Multisend /> we are changing the Accordion style we had previously.

Good point, I extracted the accordion styles into the theme as a variant and also slightly refactored `Multisend` so we don't have to prop drill as much.

2022-09-28 17:05 UTC, DiogoSoaress approved these changes
Great job here! Nice to see all the Accordion customization in the theme 🙏 

One small remark, couldn't we show the account blockie inside the Accordions as well? It identifies immediately the address

<img width="587" alt="Screenshot 2022-09-28 at 19 03 41" src="https://user-images.githubusercontent.com/32431609/192845179-d8a8e334-7c06-4da7-9fb0-980699afefdc.png">

2022-09-29 13:15 UTC, liliya-soroka commented
Returned back:
Now I don't see the list of the included txs at all
<img width="1436" alt="image" src="https://user-images.githubusercontent.com/338622/193041137-92fabfc7-e87d-4daa-8639-13e2638a090f.png">
https://0b585a55.web-core.pages.dev/rin:0xf2565317F3Ae8Ae9EA98E9Fe1e7FADC77F823cbD/transactions/queue

2022-09-29 15:32 UTC, usame-algan commented
> One small remark, couldn't we show the account blockie inside the Accordions as well? It identifies immediately the address

I like the idea and its a small change. Should we do it in this PR? It would also affect every tx detail view.

> Now I don't see the list of the included txs at all

Thanks for testing! The issue was that we were using the multiSendCallOnly contract even though one of the transaction is a delegate call. I switched to the normal multiSend contract which solved the issue.

2022-09-30 16:38 UTC, liliya-soroka commented
@DiogoSoaress , could you check this set of the tx , please - https://display-batch-execute-action.web-core.pages.dev/rin:0x938bae50a210b80EA233112800Cd5Bc2e7644300/transactions/queue ( staging CGW)
The fix worked when there were 3 tx, but doesn't work with 4 txs in the batch 
<img width="1224" alt="image" src="https://user-images.githubusercontent.com/338622/193317062-d7d053d1-0afc-4d05-bb43-e00b8fdf81f8.png">

2022-10-04 09:04 UTC, DiogoSoaress commented
> Should we do it in this PR? It would also affect every tx detail view.

Fair point. I think we can address it separately if it is really a go.

2022-10-04 13:19 UTC, DiogoSoaress commented
The block explorer icon is cut here 🤯 any idea where to get some more width?

<img width="570" alt="Screenshot 2022-10-04 at 15 17 00" src="https://user-images.githubusercontent.com/32431609/193829351-13e10ff2-a68b-4c1c-87d1-bf98d11af62e.png">

2022-10-04 13:24 UTC, DiogoSoaress commented
Can you please update the branch? We already merged this https://github.com/safe-global/web-core/pull/747 and we are not using MUI icons anymore. Plus, there are some conflicts that must be resolved

2022-10-04 13:30 UTC, DiogoSoaress commented on src/components/transactions/TxDetails/TxData/DecodedData/SingleTxDecoded/index.tsx
> +type SingleTxDecoded = {
```suggestion
type SingleTxDecodedProps = {
```

2022-10-04 13:31 UTC, DiogoSoaress commented on src/components/transactions/TxDetails/TxData/DecodedData/SingleTxDecoded/index.tsx
> +type SingleTxDecoded = {
nit

2022-10-04 14:38 UTC, usame-algan commented
> The block explorer icon is cut here 🤯 any idea where to get some more width?

Looks like it only affects some addresses depending on the character width. We looked at this problem in the past where one proposed solution was to use a monospaced font for the addresses. For now, I suggest we increase the modal width slightly even though its not an optimal solution.

2022-10-06 10:32 UTC, merged