fix: `Backdrop` `backgroundColor` based on theme
safe-global/web-core pull request #731
Opened 2022-09-29 06:51 UTC by iamacook

## What it solves

Resolves theme-based `Backdrop` `backgroundColor`

## How this PR fixes it

The `Backdrop` `backgroundColor` is set from the theme `palette`, thus reacting to light/dark mode.

## How to test it

1. Open the Safe in light mode and open the wallet popper. Observe a light background.
2. Open the Safe in dark mode and open the wallet popper. Observe a dark background.

## Screenshots

![image](https://user-images.githubusercontent.com/20442784/192959862-d1e4f53a-3c8e-4c04-8440-b077c1868c95.png)

![image](https://user-images.githubusercontent.com/20442784/192959836-d6945fe0-6503-444c-b67d-132741282bcc.png)

2022-09-29 06:52 UTC, iamacook commented on src/utils/style.ts
> +export const setOpacity = (hex: string, alpha: number) =>
Taken from [here](https://stackoverflow.com/a/66143374/6585368).

2022-09-29 07:42 UTC, usame-algan commented
I would suggest we go with a neutral color in light mode instead of green. Especially when multiple backdrops stack on top of each other its very distracting imo.
<img width="1448" alt="Screenshot 2022-09-29 at 09 41 08" src="https://user-images.githubusercontent.com/5880855/192970450-2271d247-3204-4b91-ab2b-752a32db3fee.png">

2022-09-29 07:57 UTC, iamacook commented
> I would suggest we go with a neutral color in light mode instead of green.

I've altered it to `background.main`.

2022-09-29 08:33 UTC, usame-algan requested changes

2022-09-29 08:33 UTC, usame-algan commented on src/styles/theme.ts
> +            backgroundColor: setOpacity(theme.palette.background.main || '', 0.75),
MUI ships with a util function called `alpha` which we can use: `alpha(theme.palette.background.main, 0.75)`. Do we need the fallback to ''? Afaik `background.main` is defined in both color palettes.

2022-09-29 09:06 UTC, usame-algan commented
After discussion and comparing with the [designs](https://www.figma.com/file/ptTs6lDBeUuLNySroJ5PiF/Web-Master-File?node-id=1056%3A41070) it looks like we need a new color mapping that is #303033 in light-mode and #000000 in dark-mode as the backdrop color. Imo using `background.main` already brings an improvement in dark-mode but doesn't separate the background from the modals enough in light-mode.

I suggest we merge this PR and tackle the new color mapping separately as it requires syncing with design on the color scheme. cc @TanyaEfremova

2022-09-29 09:06 UTC, usame-algan approved these changes

2022-10-04 17:50 UTC, francovenica commented
Question:
Do the backgrounds have to overlap if you open multiple modals? like if you click "new transactions > Send funds", because 2 modals were opened 2 background blur are stuck on each other. 
I'd assume that there is no way to know if there is already a background blur active.

Issue:
Opening the onboard modal to select a wallet has a different background color than any other modal like send funds.
In light mode and dark mode the background is the same color it seems
![image](https://user-images.githubusercontent.com/4503659/193890363-22b4bd85-b364-4203-b3b7-eff28bb9dceb.png)

I'd expect to have this background color 
![image](https://user-images.githubusercontent.com/4503659/193890417-7651b4c5-92dd-4e0f-9a58-3f2e485acc7a.png)

2022-10-05 08:23 UTC, iamacook commented
> Question: Do the backgrounds have to overlap if you open multiple modals?

Yes, they stack.

> Issue: Opening the onboard modal to select a wallet has a different background color than any other modal like send funds. 

It is currently not possible to customise the backdrop of onboard either.

I will therefore merge this as it is a simple CSS tweak. I'll get in touch with Blocknative and maybe we can revisit their modal backdrop in the future.

2022-10-05 08:23 UTC, merged